inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-1.0, 12.0], [-2.0, 8.0], [-2.0, 4.0]]
  marching_cubes_bound: [[-1.0, 12.0], [-2.0, 8.0], [-2.0, 4.0]]
data:
  input_folder: Datasets/scannet/scans/scene0022_00
  output: output/scannet/scans/scene0022_00
