inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-1.0, 8.0], [-2.0, 6.0], [-2.0, 3.0]]
  marching_cubes_bound: [[-1.0, 8.0], [-2.0, 6.0], [-2.0, 3.0]]
data:
  input_folder: Datasets/scannet/scans/scene0013_01
  output: output/scannet/scans/scene0013_01
