inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-1.0, 9.0], [-2.0, 5.0], [-2.0, 5.0]]
  marching_cubes_bound: [[-1.0, 9.0], [-2.0, 5.0], [-2.0, 5.0]]
data:
  input_folder: Datasets/scannet/scans/scene0007_00
  output: output/scannet/scans/scene0007_00
