inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-1.0, 10.0], [-2.0, 7.0], [-2.0, 5.0]]
  marching_cubes_bound: [[-1.0, 10.0], [-2.0, 7.0], [-2.0, 5.0]]
data:
  input_folder: Datasets/scannet/scans/scene0019_01
  output: output/scannet/scans/scene0019_01
